name: skyaotic
favicon: null
layout_spectrum: 0.86594
typography_spectrum: 0.54562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4bbb3'
    - '#04163a'
    - '#726d6a'
    - '#e1c03d'
    - '#324452'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
