name: skyaotic
favicon: null
layout_spectrum: 0.86594
typography_spectrum: 0.54562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f51b5'
    - '#ffffff'
    - '#ff5722'
    - '#ff8b67'
    - '#8ab7e8'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
