name: skyaotic
favicon: null
layout_spectrum: 0.85714
typography_spectrum: 0.54562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8197a5'
    - '#010504'
    - '#254142'
    - '#ccc9d0'
    - '#a46e4a'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 1
purpose: []
