name: skyaotic
favicon: null
layout_spectrum: 0.87225
typography_spectrum: 0.65889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22b14c'
    - '#3f51b5'
    - '#ff5722'
    - '#dc9843'
    - '#ffffff'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
