name: skyaotic
favicon: null
layout_spectrum: 0.38498
typography_spectrum: 0.34211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5746892371680588
  lightness: 0.43652085470966995
  saturation: 0.4005719751585275
  rhythmicContrast: 0.1893417714163661
purpose: []
