name: skyaotic
favicon: null
layout_spectrum: 0.85714
typography_spectrum: 0.54562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c0000'
    - '#006ee1'
    - '#00b6ff'
    - '#9ce266'
    - '#ad6a19'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
