name: skyaotic
favicon: null
layout_spectrum: 0.87225
typography_spectrum: 0.65889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75324935-1 Status
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22b14c'
    - '#3f51b5'
    - '#7092be'
    - '#ffffff'
    - '#b5e61d'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
