analytics: {}
color:
  brandColors:
    - '#000000'
    - '#4A6322'
    - '#000000'
    - '#A0C860'
    - '#C8E888'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0
name: skyaotic
opengraph: {}
purpose: []
typography_spectrum: 0.65889
