name: skyaotic
favicon: null
layout_spectrum: 0.75142
typography_spectrum: 0.28633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75324935-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22b14c'
    - '#3f51b5'
    - '#7092be'
    - '#ffffff'
    - '#b5e61d'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
