analytics: {}
color:
  brandColors:
    - '#A0B8B0'
    - '#105048'
    - '#70A898'
    - '#409080'
    - '#000000'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.509009
cta: {}
layout_spectrum: 0
name: skyaotic
opengraph: {}
purpose: []
typography_spectrum: 0.65889
