name: skyaotic
favicon: null
layout_spectrum: 0.85714
typography_spectrum: 0.66267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07081d'
    - '#ffffff'
    - '#e07a61'
    - '#403c5f'
    - '#fbcd80'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
